on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy Undaunted Staging
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.baschwar.com
        port: 21
        username: baschwar
        path: /www/frontendmentor
        password: ${{ secrets.FTP_PASSWORD }}
